name: pet_adoption_assignment
description: Local Pet adoption assignement
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  animated_snack_bar: ^0.3.1
  bloc: ^9.0.0
  flex_color_scheme: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localizations:
    sdk: flutter
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  logger: ^1.1.0
  lottie: ^3.3.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.3
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Bold.ttf
        - asset: fonts/Oxygen-Regular.ttf
        - asset: fonts/Oxygen-Light.ttf
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-ExtraBold.otf
        - asset: fonts/Montserrat-Bold.otf
        - asset: fonts/Montserrat-Medium.otf
        - asset: fonts/Montserrat-Regular.otf
        - asset: fonts/Montserrat-Light.otf
    - family: Monoton
      fonts:
        - asset: fonts/Monoton-Regular.ttf